spring:
  application:
    name: carrinhoAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/carrinhoAPI
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
api:
  prefix: /api/v1